[project]
name = 'octo_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.auto_deposit_wallet]
path = 'contracts/auto_deposit_wallet.clar'
clarity_version = 2
epoch = 2.5

[contracts.offline_vote_submission_support]
path = 'contracts/offline_vote_submission_support.clar'
clarity_version = 2
epoch = 2.5

[contracts.safe_with_access_logs]
path = 'contracts/safe_with_access_logs.clar'
clarity_version = 2
epoch = 2.5

[contracts.storage_auditor]
path = 'contracts/storage_auditor.clar'
clarity_version = 2
epoch = 2.5

[contracts.user]
path = 'contracts/user.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
